services:
  db:
    container_name: database-postgres-car-rent
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d